matrix:
- name: Markdown
  aspell:
    lang: es
    ignore-case: true
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '*.md'
  default_encoding: utf-8
